CREATE DATABASE BD_TRANSPORTADORA
GO;

USE BD_TRANSPORTADORA
GO;

CREATE TABLE PESSOAS (
	ID INT PRIMARY KEY IDENTITY NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	RG VARCHAR(20),
	CNH VARCHAR(20),
	EMAIL VARCHAR(50) NOT NULL,
	ENDERECO VARCHAR(50),
	NUMERO INT,
	BAIRRO VARCHAR(20),
	CEP VARCHAR(9),
	CIDADE VARCHAR(50),
	UF VARCHAR(2),
	FONE_1 VARCHAR(14) NOT NULL,
	FONE_2 VARCHAR(14),
	SITUACAO VARCHAR(10) NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
);


CREATE TABLE USUARIOS (
	COD_USUARIO INT PRIMARY KEY IDENTITY NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SENHA VARCHAR(8) NOT NULL,
	NIVEL VARCHAR(15) NOT NULL,
);


CREATE TABLE VEICULOS (
	COD_VEICULO INT PRIMARY KEY IDENTITY NOT NULL,
	MODELO VARCHAR(50) NOT NULL,
	PLACA VARCHAR(7) NOT NULL,
	ANO_FABRICACAO INT NOT NULL,
	SITUACAO VARCHAR(10),
	COR VARCHAR(10),
	OBSERVACAO VARCHAR(200)
);


CREATE TABLE CARGAS (
	COD_CARGA INT PRIMARY KEY IDENTITY NOT NULL,
	TIPO_CARGA VARCHAR(50) NOT NULL,
	PESO NUMERIC(15,2) NOT NULL,
	LARGURA NUMERIC(15,2) NOT NULL,
	COMPRIMENTO NUMERIC(15,2) NOT NULL,
	ALTURA NUMERIC(15,2) NOT NULL,
	VALOR_UNITARIO NUMERIC(15,2) NOT NULL
);


CREATE TABLE ROTAS (
	COD_ROTA INT PRIMARY KEY IDENTITY NOT NULL,
	COD_ROTA_ITEM INT NOT NULL,
);


CREATE TABLE ROTAS_ITEM (
	COD_ROTA_ITEM INT NOT NULL,
	PONTO_PARADA VARCHAR(50) NOT NULL,
	TEMPO_CHEGADA DATE NOT NULL,
);


CREATE TABLE ORDEM_TRANSPORTE_ITEM (
	COD_ORDEM_TRANSPORTE_ITEM INT PRIMARY KEY IDENTITY NOT NULL,
	COD_CARGA INT NOT NULL,
	CONSTRAINT FK_CARGA FOREIGN KEY(COD_CARGA) REFERENCES CARGAS(COD_CARGA)
);


CREATE TABLE ORDEM_TRANSPORTE (
	COD_ORDEM_TRANSPORTE INT PRIMARY KEY IDENTITY NOT NULL,
	COD_ORDEM_TRANSPORTE_ITEM INT NOT NULL,
	COD_VEICULO INT NOT NULL,
	COD_MOTORISTA INT NOT NULL,
	COD_ROTA INT NOT NULL,
	COD_CLIENTE INT NOT NULL,
	COD_USUARIO INT NOT NULL,
	ENDERECO VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL,
	BAIRRO VARCHAR(20) NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	UF VARCHAR(2) NOT NULL,
	DATA_EMISSAO DATE NOT NULL,
	DATA_SAIDA DATE NOT NULL,
	DATA_PREVISAO DATE NOT NULL,
	VALOR_TOTAL NUMERIC(15,2) NOT NULL,
	SITUACAO_TRANPORTE VARCHAR(10),
	CONSTRAINT FK_VEICULO FOREIGN KEY(COD_VEICULO) REFERENCES VEICULOS(COD_VEICULO),
	CONSTRAINT FK_MOTORISTA FOREIGN KEY(COD_MOTORISTA) REFERENCES PESSOAS(ID),
	CONSTRAINT FK_ROTA FOREIGN KEY(COD_ROTA) REFERENCES ROTAS(COD_ROTA),
	CONSTRAINT FK_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES PESSOAS(ID),
	CONSTRAINT FK_USUARIO FOREIGN KEY(COD_USUARIO) REFERENCES PESSOAS(ID),
);


CREATE TABLE BAIXA_ORDEM_TRANSPORTE (
	COD_BAIXA_ORDEM_TRANSPORTE INT PRIMARY KEY IDENTITY NOT NULL,
	COD_ORDEM_TRANSPORTE INT NOT NULL,
	DATA_CHEGADA DATE NOT NULL
);